<template>
  <section class="section">
    <div class="container">
      <div class="message is-info is-bold is-medium" v-if="!auth">
        <div class="message-header">
          <h1 class="title has-text-white">Sign in, and let's get started!</h1>
        </div>
        <div class="message-body">
          <p class="subtitle">This is required to prevent abuse.</p>
          <a class="button" style="margin-bottom:10px" @click="login">Log In - Gmail</a>
        </div>
      </div>
      <div v-if="auth">
        <slide v-if="count == 0" :slideSubject="'0: Hello ' + firstName + '!'" :slideContent="[{line: 'This course is meant to guide you through the beginnings of HTML by building a simple resume!'},{line: 'Initially, it was meant to be a meetup run in Vancouver by some Canada Learning Code teen ambassadors (of which I [Kewbish] am one!), but due to COVID-19, it was cancelled.'},{line: 'If you wish to support Canada Learning Code, whose mission is to bring the power of technology to all, including historically underrepresented groups in tech, please visit the following link:'},{list: [{item: 'Canada Learning Code', link:'https://canadalearningcode.secure.nonprofitsoapbox.com/clc-donate'}]},{line: 'This course was created by Emilie Ma - also known as Kewbish. If you\'d like to learn more about me, visit:'},{list: [{item: 'My site', link:'https://kewbish.github.io'}]},{line: 'Time to get started on your web development journey! First, let\'s download some software.'},{line: 'You\'ll need some software to get started. We\'ll use:'},{list:[{item: 'VSCode', link: 'https://code.visualstudio.com/download'}, {item: 'VSCode HTML Preview', link: 'https://marketplace.visualstudio.com/items?itemName=tht13.html-preview-vscode'}, {item: 'Any web browser, like Chrome'}]},{line: 'Once you\'ve downloaded everything, press the [>] button - it\'s time to go!'}]"/>
        <slide v-else-if="count == 1" slideSubject="1: Creating your files" :slideContent="[{line: 'Every website starts with an index.html file. This is what all web browsers look for to start rendering your creation within a site\'s files when it loads up.'},{line: 'Create a folder on your computer, and open this folder with VSCode by clicking this button:'}, {img: ['https://i.stack.imgur.com/AlsoM.png', 'Figure 1: Open the folder you just created.']}, {line: 'Now, it\'s time to create an index.html file.'},{img: ['https://code.visualstudio.com/assets/docs/nodejs/nodejs/toolbar-new-file.png', 'Figure 2: Create a new file, and call it index.html.']},{line:'You\'ll need to do the same with a main.css file. Create a main.css file, just like you created your index.html file.'}]"/>
        <slide v-else-if="count == 2" slideSubject="2: Some basic tags" :slideContent="[{line:'The current HTML version is HTML5, and to denote that, we\'ll need to add a <!DOCTYPE HTML> tag.'},{line:'Luckily, VSCode comes with something called Emmet abbreviations to streamline starting up a blank file. Type \'html:5\', and select the Emmet Abbreviation that pops up with [Enter].'},{line:'VSCode should spit a nice template out for us. If not: copy-paste the code below.'},{code:'<!DOCTYPE html>\n<html lang=&quot;en&quot;>\n<head>\n\t<meta charset=&quot;UTF-8&quot;>\n\t<meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot;>\n\t<title>Document</title>\n</head>\n<body>\n</body>\n</html>'}, {line: 'The <head> elements are meta elements, and we don\'t have to worry about anything right now except the <title></title>. That\'s what you\'ll see in the address bar, so choose something like your name.'}, {img: ['https://i.imgur.com/cB42RYe.png', 'Figure 3: The HTML + CSS is where your title would go.']}]"/>
        <slide v-else-if="count == 3" slideSubject="3: Learning about <p>, <h1>, and <a>" :slideContent="[{line: 'Within your <body></body> tags, try adding some other tags.'},{line:'Try pressing [Ctrl-Shift-V] to open the HTML preview, and refer to it as we go through each tag.'},{line: 'First, we\'ll look at the <p>. Add it within the body, and add something inside so it looks something like:'},{code: '<p>Hello there!</p>'},{line: 'The </p> slash is required - it denotes the ending of a tag.'},{line: 'Try doing the same with <h1> tags! Remember the </h1> tag!'},{line: 'In your preview, what do these do? [Spoiler: <p> creates paragraphs, and <h1> headers.]'},{line: 'Let\'s also go through the concept nesting: with the <a> tag.'},{code: '<a href=&quot;https://reddit.com&quot;><p>This link goes to Reddit</p></a>'},{line: 'See how the <a> tag goes *around* the <p> tag? This is called nesting, and the <a> is now the parent of the <a> tag, the child. We\'ll go through this in greater detail once we start structuring our site.'},{timer:['Experiment with these tags', 'Try playing around with the <a> link tags, and get familiar with how to add <p> and <h1> tags, as well as how to close them.', 180]}]"/>
        <slide v-else-if="count == 4" slideSubject="4: Structural elements: <div> and <section>" :slideContent="[{line:'<div> and <section> won\'t have any visible effect on the structure, and don\'t print anything like <h1> and <p>. However, they\'re still required as basic knowledge.'},{line: 'Section tags allow us to differentiate different, well, sections in your website. It can contain any other tags, like <div>, <h1>, and <p>.'},{line: 'Speaking of which: what does the div tag do? It\'s a container, and like section, can contain any other HTML tags, including another div.'},{line: 'Visibly, these don\'t seem to do anything, but we\'ll be using them very frequently to structure our web resume.'},{line: 'Unfortunately, we\'ll have to undo all your hard work - but that\'s alright, you\'ve learned so much!'},{line: 'Inside your <body>, add a couple of <sections>.'}, {code: '<section class=&quot;header&quot;></section>\n<section class=&quot;about-me&quot;></section>\n<section class=&quot;education&quot;></section>\n<section class=&quot;project-skills&quot;></section>\n<section class=&quot;footer&quot;></section>\n'},{line:'This will add several empty sections to your site. Remember, you can preview your site with [Ctrl-Shift-V]!'}]"/>
        <slide v-else-if="count == 5" slideSubject="5: Filling up .about-me" :slideContent="[{line: 'Let\'s fill up our .about-me with content. Inside the <section> tags, type:'}, {line: '[Tip]: Type this code out by hand - it helps you learn much better. Copy-paste doesn\'t teach your brain to HTMLify :)'}, {code: '<div class=&quot;about-me-image&quot;>\n\t<img src=&quot;https://imgur.com/helloWorld&quot;>\n</div>\n<h1>Hey - I\'m [yourname]</h1>\n<div class=&quot;custom-div&quot;></div>\n<p>This is where you can briefly touch on your life, thoughts, and manifestos.</p>'}, {line: 'Here, a new tag is introduced: the <img> tag. This is one of the few tags in HTML that doesn\'t require an ending / tag. We need a src property - replace this with an imgur link, after you upload your profile headshot, of course.'}, {line: 'Let\'s see how your site is looking so far! [Ctrl-S] to save, and [Ctrl-Shift-V] to view.'}, {img: ['https://i.imgur.com/bPBFH7F.png', 'Figure 1. Your site so far. Not much, eh?']}]"/>
        <slide v-else-if="count == 6" slideSubject="6: Filling up the rest of our sections" :slideContent="[{line: 'For the next 15-20 minutes, work on filling in content around your website. Try editing your education details, writing about your work, or changing anything else you wish. (Don\'t worry about the projects bit quite yet - we\'ll learn how to build a grid with that soon!)'},{line: 'Don\'t feel limited by the section classes we have implemented here, you can add sections with classes with whatever you wish!'}, {timer:['Editing time!', 'Change anything and everything about the site, right now. Add headings, paragraphs, text, images, whatever you like.', 1200]}]"/>
        <slide v-else-if="count == 7" slideSubject="7: Checkin + break!" :slideContent="[{line: 'Time for our first checkin!'}, {line: 'In the past section, we\'ve learned to:'}, {list: [{item: 'Using a code editor - easy shortcuts like [Ctrl-S] and [Ctrl-Shift-V]'},{item: 'Basic HTML tags - <p>, <div>, <a>, <img>, <h1>, <section> (and maybe you\'ve come across others too!)'}, {items:'Structuring a site, and applying classes'}]}, {line: 'In the next section, we\'ll be learning how to style our site, as well as what those class quotes really do.'}, {line: 'By now, your site might look something like:'},{img:['https://i.imgur.com/hQ6i5jj.png', 'Figure 1: Just an example - we\'ll style it up soon!']},{line: 'Oh - it\'s been a while already, remember to stand up, stretch, and take your eyes off the screen before we get started on CSS!'}]"></slide>
        <slide v-else-if="count == 8" slideSubject="8: A whole new style" :slideContent="[{line: 'We\'re about to get started with a whole new language - CSS. CSS stands for Cascading Style Sheets, and is the language that web browsers use to figure out how to color, shape, and format your content.'},{line: 'To get started, add a main.css file. As with the index.html, click the File add icon on the sidebar of VSCode, and add the file.'},{line: 'To link our index.html with our main.css file, add the following link inside your <head> element:'},{code: '<link rel=&quot;stylesheet&quot; href=&quot;main.css&quot;>'},{line: 'This will ensure that any styling changes you add to your site is reflected when you view your site with [Ctrl-Shift-V].'},{line: 'Let\'s start off simple: by styling our <h1> tags. In CSS, styling all elements of a tag type (here, all <h1>s), is done by adding:'},{code:'h1{\n\t//something_here\n}'},{line: 'Times New Roman is a boring font - find a new one from:'},{list:[{item: 'Google Fonts', link:'https://fonts.google.com/'}]},{line: 'Choose one, select style, and copy the embed tag into your <head>, just like you added the link to the main.css file. Now, we\'ll add it to the HTML.'},{code:'h1{\n\tfont-family:fontname;\n\tfont-size:18px;\n\tcolor:mediumblue;\n}'},{line: 'Make sure you change the fontname to the actual name of the font you\'ve just imported. Now, you\'ll have something like:'},{img:['https://i.imgur.com/qB2idJq.png', 'Figure 1: An example of our shiny new blue headers!']},{line: 'font-family, font-size, and color are all examples of CSS properties that describe what an element looks like. A great reference can be found here:'},{list:[{item: 'W3schools', link:'https://www.w3schools.com/css/default.asp'}]},{line: 'These colours and parameters can all be changed to whatever you wish. Experiment and have fun!'}]"/>
        <slide v-else-if="count == 9" slideSubject="9: Dividers and box model" :slideContent="[{line: 'CSS structures most elements in HTML with a box model.'},{img:['https://miro.medium.com/max/1400/1*gq1B7v2_gDEi3jkAwAvZNQ.png', 'Figure 1: The CSS box model. Every element has its content, padding, margin, and border.']},{line:'Here, we\'ll be taking advantage of the border to add a nice divider element.'},{line:'Already implemented in the code is a .custom-div class, which we\'ll use in CSS to add a solid divider.'},{code: '.custom-div{\n\tborder-bottom:1px solid darkgray;\n}'},{line: 'The . before the custom-div style tells CSS that we\'re referencing a class. [There are also id\'s, but we won\'t be going over those in this intro site.] The border-bottom is another property that adds a 1 pixel tall, solid, dark gray border to the .custom-div element. Now, your site might look something like:'},{img:['https://i.imgur.com/pSvBuao.png', 'Figure 2: Maybe your site looks like this! Note the long border going across.']}]"/>
        <slide v-else-if="count == 10" slideSubject="10: Centering both ways" :slideContent="[{line: 'Commonly, we also see elements centered on webpages. Let\'s learn how to do that, applying our new knowledge with element and class selectors. (Remember, the h1{} and the .about-me{}?)'},{line:'To center content horizontally, like:'},{code:'|   [el]   |'},{line:'We can use the following CSS - again, taking advantage of the margin properties of each element.'},{code:'.class{\n\tmargin: auto;\n\ttext-align: center;\n}'},{line: 'The auto margin sets the margin automatically on each side of the element with the class \'class\', top, right, left, and bottom. This doesn\'t end up affecting your top or bottom (we\'ll get there soon)'},{line:'The text-align property aligns the text within the div. If you don\'t want your text centered in your centered div, you don\'t need to add this.'},{line: 'Try applying this to one of your classes or elements!'},{line:'Now, let\'s go over vertical centering. Usually, this ends up being a little more tricky than horizontal centering.'}, {code:'.class{\n\tmargin: 0 auto;\n}'}, {line: 'This sets the margin of the top and bottom to zero, and therefore sets the element right in the middle of its parent. That\'s usually the de-facto solution, but alternatively, you can choose to use:'},{code: '.class{\n\tposition: relative;\n\ttop: 50%;\n\ttransform: translateY(-50%);'},{line: 'This is another solution - it sets the position (usually static where elements render in order) to relative to its parent element. It positions 50% away from the top, and then 50% of the element\'s height back up, to properly center.'},{line: 'Note: if you try to center an image, you usually need to put it inside a div, and apply the class to that div instead. This is due to the fact that images don\'t render as blocks properly, and have some weird margin styles.'},{line: 'If you\'d like to center elements, take the next couple minutes to apply some styles!'},{timer: ['Centering', 'Take the next while to center some of your elements with what you\'ve just learned.', '150']}]"/>
        <slide v-else-if="count == 11" slideSubject="11: Going over some easy properties" :slideContent="[{line: 'Alright, speed round. These are some easy-to-understand CSS properties that are commonly used, but don\'t need a lot of explanation.'}, {code:'.class{\n\tbackground-color: #123456;\n}'},{line: 'This sets the background color of your element to a hex code. You can find a hex code for any color from Google - just look up a hex color picker. To add a background image instead:'},{code:'.class{\n\tbackground: url(\'url/to/jpeg\');\n}'},{code:'.class{\n\ttext-shadow: 2px 2px #123456;\n}'},{line: 'This sets a text shadow to a text element, 2px left-right, and 2px top-down away. These values can be negative, too. Again, there\'s the hex code - set it to your desired text shadow color.'},{code:'.class:hover{\n\tcolor: #123456;\n}'},{line:'This is a little different. The :hover selector goes after an element or class selector. Here, the style would be applied when the element with class \'class\' was hovered over. Here, we\'re just setting an arbitrary color, but other properties can be applied, like text-shadow, for example.'},{timer:['Try out some of these new properties!', 'If you\'re happy with how your site looks now, you can skip this.', 240]}]"/>
        <slide v-else-if="count == 12" slideSubject="12: Learning CSS Grid" :slideContent="[{line: 'If you\'ve ever seen some grid layouts like:'},{img: ['https://speckyboy.com/wp-content/uploads/2017/09/css-grid-layouts-03.jpg', 'Figure 1: A cool grid layout example!']},{img: ['https://designinginterfaces.com/wp-content/images/grid-of-equals-cnn.png', 'Figre 2: Another example, something closer to what we\'ll be building for our projects section.']},{line: 'Before we do any cool CSS styling, we need to structure our grid. Add this in one of your sections in your main.html:'}, {code:'<div class=&quot;grid-container&quot;>\n\t<div>\n\t\t<h1>An item title!</h1>\n\t\t<p>An item subtitle and content. Fill this in!</p>\n\t</div>\n\t<div>\n\t\t<h1>An item title!</h1>\n\t\t<p>An item subtitle and content. Fill this in!</p>\n\t</div>\n\t<div>\n\t\t<h1>An item title!</h1>\n\t\t<p>An item subtitle and content. Fill this in!</p>\n\t</div></div>'},{line: 'Remember, the larger <div> has the class \'grid-container\', and we just filled it with three smaller <div>s which will have all our content!'},{timer: ['Feel free to edit everything!', 'Take the next couple minutes to talk about your projects, core competencies, internships, work experience, skills, interests - whatever!', 180]}]"/>
        <slide v-else-if="count == 13" slideSubject="13: Formatting the grid" :slideContent="[{line:'Alright, let\'s go back to CSS for a bit. Add the following code to your main.css file.'},{code:'.grid-container{\n\tdisplay:grid;\n\tgrid-template-columns: 1fr 1fr 1fr;\n}'},{line:'This style changes the display property of the parent (container) <div>, which is usually block, to grid. This is a relatively new CSS property, with its history only going back to around 2011. Then, we add the template columns, setting each one equal to one third each - (what the 1fr does: it\'s literally just 1 fraction of the total width.) Now, if you view your site with [Ctrl-Shift-V], you\'ll see that your <div>\'s children are displayed like so:'},{img:['https://i.imgur.com/ICfGPf1.png','Figure 1: An example grid.']},{line:'Try styling the background colors of some of the containers by adding classes, or change the font color! If you need a refresher, visit the past slides.'}]"/>
        <slide v-else-if="count == 14" slideSubject="14: Media Queries and Responsiveness" :slideContent="[{line: 'You might have tried to go to some websites on mobile, and seen that they were completely and utterly broken. However, other sites that were designed with mobile devices in mind - like Youtube, for example, look a little different, but still look, well, like Youtube.'},{line: 'For our resume, the thing that\'s most likely to break or look weird is our grid. On mobile, the text will be squished into short, tall lines. Instead, let\'s set some things called media queries, which check for the width of the screen and adapt our CSS accordingly.'},{line: 'As a separate part of your CSS, add:'},{code:'@media (min-width: 768px) and (max-width: 1024px){\n\t.grid-container{\n\t\tgrid-template-columns: 1fr 1fr;\n\t}\n}'}, {line:'This checks for tablets, which usually have a screen width of between 768 to 1024px. Then, we set our grid template to only have 2 columns to make reading easier on tablet.'},{code:'@media (min-width: 481px) and (max-width: 767px){\n\t.grid-container{\n\t\tgrid-template-columns: 1fr;\n\t}\n}'}, {line:'This checks for phone screens in portrait. Here, we only want one column, or else the text might be a little cluttered and hard to read.'},{line: 'Try previewing your site now, and resizing the side window. Alternatively, open the HTML file from File Explorer in Chrome, and resize that window. If all went well, the amount of columns will shift!'}]"/>
        <slide v-else-if="count == 15" slideSubject="15: Finishing our design" :slideContent="[{line: 'We\'re almost done, so it\'s time to finalize your design for now. Implement any and all of the properties and selectors we\'ve learned about.'},{line:'Some interesting resources you might also want to check out include:'},{list:[{item:'CSS.cool', link:'http://css.cool/#/'}, {item: 'W3schools', link:'https://www.w3schools.com/css/default.asp'}, {item: 'CSS Cookbook', link: 'https://developer.mozilla.org/en-US/docs/Web/CSS/Layout_cookbook'}]},{timer:['Take the next 5 minutes to finalize everything!', 'Make sure your site includes all the information you want on it, and if this isn\'t enough time - keep working!', 300]}, {line: 'Once you\'re done, remember to take a stretch break before we get finished with deployment.'}]"/>
        <slide v-else-if="count == 16" slideSubject="16: GitHub setup" :slideContent="[{line: 'To host our site and get a free domain, we\'ll be using a free-to-use service called GitHub and its website hosting service, GitHub Pages. Go to:'},{list:[{item: 'GitHub.com', link:'https://github.com'}]},{line: 'and sign up for an account. A free user account will work fine!'}, {line:'Next, we\'ll make our first repo, which is where we\'ll upload our code. Click the + button next to your profile picture in the top right, and fill in the next page.'},{line:'Make sure your repository name is \'[your-username].github.io\'. For example, my username is kewbish, so I\'d fill kewbish.github.io in for the repo name. The rest of the information doesn\'t matter - just make sure it\'s a public repository.'}]"/>
        <slide v-else-if="count == 17" slideSubject="17: Going live" :slideContent="[{line: 'First, let\'s upload our files. Find the Upload files button, and upload all the files in your development folder. Make sure you get your index.html and main.css, along with whatever else you\'ve added.'},{line:'Fill in whatever you\'d like for the commit message: Usually, it should be something like \'Initial commit\'. Then, click the commit button.'},{line: 'We\'re almost there. Finally, we need to enable GitHub Pages.'},{line:'Navigate to the Settings tab, and find the GitHub Pages section. Under source, select the master branch.'},{line:'Wait a couple minutes for your site to go live, and your site will be officially online and accessible at \'[your-name].github.io\'.'},{line:'Once it uploads, you can send this link to your friends and family. In the meantime, showcase your files to whoever\'s around!'},{line: 'Congratulations - you\'ve just created a website! That\'s a great accomplishment, and it\'s the first step in becoming a full-fledged web developer!'},{line:'Think about the past hour or two: we\'ve gone over HTML structure, sections, grids, and elements; CSS grids, selectors, properties, and media queries; and GitHub version control and site deployment. That\'s a ton of learning!'}]"/>
        <slide v-else slideSubject="Oops - that slide doesn't exist." :slideContent="[{line: 'Let\'s go back. Try entering the slide number you were at before. To go back to the beginning, type \'0\' in the text-input below.'}]"></slide>
      </div>
    </div>
    <input v-if="auth" type="text" class="input fixed-input" v-model="count" />
    <button v-if="auth" @click="countDown" class="button fixed-back is-small">&lt;</button>
    <button v-if="auth" @click="countUp" class="button fixed-right is-small">&gt;</button>
    <div class="fixed-right-bottom">
        <table>
            <tr>
                <td>
                    <a href="https://covid19responsefund.org/" class="button is-info" style="margin-right: 5px;">Donate to COVID 🦠</a>
                </td>
                <td>
                    <a href="https://canadalearningcode.secure.nonprofitsoapbox.com/clc-donate" class="button is-danger">Support CLC 🍁</a>
                </td>
            </tr>
        </table>
    </div>
  </section>
</template>

<script>
import Firebase from "../firebase.js";
export default {
  name: "Learn",
  data() {
    return {
      user: {
        logged: false,
        data: {}
      },
      count: 0
    };
  },
  computed: {
    auth() {
      return this.user.logged;
    },
    firstName() {
      if (this.user.data.displayName) {
        return this.user.data.displayName.split(" ")[0];
      }
      return null;
    }
  },
  methods: {
    login() {
      Firebase.login();
    },
    countUp() {
      this.count++;
    },
    countDown() {
      if (this.count > 0) {
        this.count--;
      }
    }
  },
  mounted: function() {
    Firebase.auth.onAuthStateChanged(user => {
      if (user) {
        this.user.logged = true;
        this.user.data = user;
      } else {
        this.user.logged = false;
        this.user.data = {};
      }
    });
  }
};
</script>